services:
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    container_name: mariadb_container
    restart: always
    volumes:
      - mariadb_volume:/var/lib/mysql
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_password
    networks:
      - inception_network

  nginx:
    build: ./requirements/nginx
    container_name: nginx_container
    image: nginx
    ports:
      - "443:443"
    restart: always
    volumes:
      - wordpress_volume:/var/www/wordpress
    networks:
      - inception_network
    depends_on:
      - wordpress

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress_container
    image: wordpress
    restart: always
    volumes:
      - wordpress_volume:/var/www/wordpress
    env_file:
      - .env
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    networks:
      - inception_network
    depends_on:
      - mariadb

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_password:
    file: ./secrets/db_password.txt
  wp_admin_password:
    file: ./secrets/wp_admin_password.txt
  wp_user_password:
    file: ./secrets/wp_user_password.txt

networks:
  inception_network:
    name: inception_network
    driver: bridge

volumes:
  mariadb_volume:
    name: mariadb_volume
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DATA_PATH}/mariadb
  wordpress_volume:
    name: wordpress_volume
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DATA_PATH}/wordpress
